<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="s1" duration-ms="13336" started-at="2018-11-19T08:07:05Z" finished-at="2018-11-19T08:07:19Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="13336" started-at="2018-11-19T08:07:05Z" finished-at="2018-11-19T08:07:19Z">
      <class name="com.webtest.demo.Grbg_Test">
        <test-method status="PASS" signature="doBeforeSuite()[pri:0, instance:com.webtest.demo.Grbg_Test@12cdcf4]" name="doBeforeSuite" is-config="true" duration-ms="10293" started-at="2018-11-19T08:06:55Z" finished-at="2018-11-19T08:07:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeSuite -->
        <test-method status="FAIL" signature="dakaSuccess()[pri:0, instance:com.webtest.demo.Grbg_Test@12cdcf4]" name="dakaSuccess" duration-ms="13117" started-at="2018-11-19T08:07:05Z" description="测试" finished-at="2018-11-19T08:07:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.webtest.demo.Grbg_Test.dakaSuccess(Grbg_Test.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dakaSuccess -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:com.webtest.demo.Grbg_Test@12cdcf4]" name="doAfterMethod" is-config="true" duration-ms="445" started-at="2018-11-19T08:07:19Z" finished-at="2018-11-19T08:07:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- com.webtest.demo.Grbg_Test -->
    </test> <!-- test1 -->
  </suite> <!-- s1 -->
</testng-results>
